### ISSUE TITLE
Copy S3 file rather than download + upload

### ISSUE THREAD

**Issue by lloydwatkin** [equivalent/copy_carrierwave_file#11]
Question: In https://github.com/equivalent/copy_carrierwave_file/blob/master/lib/copy_carrierwave_file/copy_file_service.rb, do you think it would be possible to use an S3 copy object call, rather than downloading and (re)uploding the image?  This should be much quicker and less resource intensive on the server.

**Comment by equivalent** [comment]
Hi, 

well theoretically you could create some kind of script that would do equivalent of [AWS S3 CLI](https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html) `aws s3 cp s3://my-bucket/mount-a/file.jpg s3://my-bucket/mount-b/` and then just update filename DB column value in Rails app 

but the thing is this is quite custom to do. I'm pretty sure it would work but creating generic solution fore everyone is super  hard to get right - out of the scope of this (lazy) gem :)

**Comment by lloydwatkin** [comment]
Thought so, but worth asking. Thanks!
