### ISSUE TITLE
Image doesn't copy physically in directory

### ISSUE THREAD

**Issue by Bilkhaan** [equivalent/copy_carrierwave_file#7]
Hi, I am trying to replicate the image from one record to another record. I have used amoeba gem to make duplicate of the record. I have used your gem to copy the carrierwave uploaded image to the duplicated record. But it just assign the name and file path to the duplicated record and doesn't copy the actual image physically in the directory.

I am using local storage to store the images, as i am trying it on development for now. In my carrierwave config file i am using:

config.storage = :file
   config.cache_dir = "uploads/tmp"
    config.fog_directory  = ENV["AWS_BUCKET"]                          # required
    config.fog_public     = false                                        # optional, defaults to true
    config.fog_attributes = { 'Cache-Control' => "max-age=#{365.day.to_i}" } # optional, defaults to {}
    config.storage = :fog
 
And in my model i am using:

`CopyCarrierwaveFile::CopyFileService.new(self, eap, :eap_image).set_file`

Can you please look into this issue. Thanks

**Comment by equivalent** [comment]
thank you for reporting I'll look into this during this weak, can you just please let me know what Ruby or Rails, Carrierwave and Ruby version are you using so I can try to replicate this 

thank you

**Comment by Bilkhaan** [comment]
I am using ruby version '2.2.3' and rails version '4.2.4' with carrierwave version '0.11.2'. That would be great. Looking forward to your response.

**Comment by Bilkhaan** [comment]
Hi, @equivalent  did you find any solution for the mentioned issue? 

Thanks

**Comment by equivalent** [comment]
I'll look at it on Sunday

**Comment by Bilkhaan** [comment]
No problem at all. take your time (Y)

**Comment by Bilkhaan** [comment]
Hi, i have figured out the issue. As it was somehow my mistake. The documentation for the gem says the record in which we want to replicate the carrierwave image should be a new instance. What i was doing wrong was to use already created record and try to replicate the carrierwave image for that record. But the record already have the image value set which some how does't allow the new replicated value. So I have updated my code to use new instance in that case.

Thanks for the gem, much appreciated :)

**Comment by equivalent** [comment]
aaaaw :) ok that make sence :) good to know. 

Nice spot. 

No problem glad that you find use for it  ;)

**Comment by ngelx** [comment]
This is a very important kaveat, as a typically use case that will not work is:

```ruby
something2 = something.dup
CopyCarrierwaveFile::CopyFileService.new(something, something2, :mount_point).set_file
something2.save!
```

Instead of that, something like must be done:

```ruby
fitlered_attributes = something.attributes.reject { |key, _| %w(id mount_point).include? key }
something2 = something.class.new(filtered_attributes)
CopyCarrierwaveFile::CopyFileService.new(something, something2, :mount_point).set_file
something2.save!
```
